### ISSUE TITLE
Survey questions - multiple sets

### ISSUE THREAD

**Issue by AkiliDaniels** [raven-black-dream/base45-svelte#33]
When a set is added, burn question and how difficult question appear after set 2, sore joints question and pump question appear after set 3.

Also noticed that after some exercises have 3 sets, exercises with 2 sets only offer two questions and not all four. (Specific questions may be incorrect, but gist is that 2 questions appear and 2 do not. Issue is also inconsistent)

**Comment by raven-black-dream** [comment]
This should be resolved as a part of one of the changes that I made today.
