### ISSUE TITLE
Progress wheel

### ISSUE THREAD

**Issue by AkiliDaniels** [raven-black-dream/base45-svelte#34]
**Describe the bug**
Progress wheel on home page resets to zero after last workout in the week - doesn't show 100%

**To Reproduce**
Mark Sunday's workout complete
View home page

**Expected behavior**
For it to show 100% completion until start of "new week"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Pixel 8
- Chrome browser

**Additional context**

**Comment by raven-black-dream** [comment]
Should be resolved by changes made today
